### ISSUE TITLE
Gestione Codice ufficio PA e dati Cedente/Commissionario

### ISSUE THREAD

**Issue by Deltafox79** [FatturaElettronica/FatturaElettronica.Forms#1]
@nicolaiarocci  e Diego ecco la classe completa per la richiesta dei dati della PA con il ritorno in formato Json

La classe prevede tutti i possibili campi in ritorna su tutte e 7 le possibilità di ricerca possibile.. da questi dati è possibile compilare in automatico il campo "Codice Ufficio PA" equivalente al "cod_uni_ou" o "cod_entita" e anche i campi della sezione Cedente Commissionario..

Che ne pensate?

Saluti

**Comment by nicola** [comment]
hey @Deltafox79, puoi utilizzare il correct handling per @nicolaiarocci ?

**Comment by nicolaiarocci** [comment]
@nicola ecco chi mi ha fregato l'handle corto su github! :smile: 
Scusa lo spam.

**Comment by Deltafox79** [comment]
@nicolaiarocci e Diego Corretto delle eccezioni ecco la classe completa per la richiesta dei dati della PA con il ritorno in formato Json

Home Project

http://pastebin.com/u9aSvy6g

e source class

http://pastebin.com/G97sb7Gn

Esempio .:

http://i.imgur.com/cxkRav1.jpg?1

La classe prevede tutti i possibili campi in ritorna su tutte e 7 le possibilità di ricerca possibile.. da questi dati è possibile compilare in automatico il campo "Codice Ufficio PA" equivalente al "cod_uni_ou" o "cod_entita" e anche i campi della sezione Cedente Commissionario..

Che ne pensate?

Saluti

**Comment by nicolaiarocci** [comment]
Intanto grazie per il lavoro svolto. Alcune domande:

- AUTH_ID, che tu sappia, è temporaneo o permanente? 
- Ci sono vincoli di accesso per ogni AUTH_ID, tipo rate limiting (numero di richieste/ora/giono/minuto)?

In generale sono perplesso dall'inserire direttamente in **Forms** queste funzionalità, principalmente perché dipendono dall'accesso ad un servizio esterno che, pure essendo PA, potrebbe causare problemi che poi non possiamo controllare (lentezza; non accessibilità; cambio della API con conseguente rottura del nostro codice; ecc.)

Detto questo, vedrei bene un package WebServicePA (o qualcosa del genere) che potrebbe essere adottato da chi lo desidera. Potremmo ospitarlo all'interno della org FatturaElettronicaPA naturalmente.

Se ben congegnato un package come questo potrebbe anche diventare una dipendenza opzionale sia di  **FatturaElettronicaPA** che di **Forms**. Per esempio: 

 - **FatturaElettronicaPA** potrebbe avere un nuovo Validator per convalidare il Codice ufficio PA (se una proprietà AUTH_ID è impostata). In questo modo tutto rimane come è ora a meno che non si voglia esplicitamente fare questa convalida;
 - **Forms** potrebbe implementare compilazione automatica dei campi CedenteCommissionario (anche qui fornendo opt-in, per via di proprietà da settare esplicitamente)

Che ne pensate?

**Comment by Deltafox79** [comment]
@nicolaiarocci  rispondo

1) AUTH_ID è pemanente ma ognuno può richiedere ed inserire il suo personale basta richiederlo
2) Nessun vincolo di nessun genere

Anche se accesso ad un servizio esterno che è e rimane comunque governativo e specifico per questo tipo di software.. che non avrebbe neanche più senso se tale sito non esistesse più cosi come i suoi servizi..  non credo causi nessun tipo di lentezza o chissà che al software per i motivi seguente..

1) la richiesta webClient viene effettuata solo se l'utente non conosce già il codice ipa quindi dal software può ricercarlo e la richiesta è immediata al massimo per essere sicuri si può impostare un timeout di qualche sec ed un catch che mostrino a video l'impossibilità di ricercare il codice..

Per me o in libreria o hard coded è ininfluente se vuoi fare un test :+1: 
https://www.dropbox.com/s/nxsul8kstl851bi/WebService_DFoX_v1.1.rar?dl=0

Ciao

**Comment by Deltafox79** [comment]
@nicolaiarocci Aggiunto timeout su richiesta web..

http://pastebin.com/GxW8yNBM

Ciao

**Comment by nicolaiarocci** [comment]
> 1) AUTH_ID è pemanente ma ognuno può richiedere ed inserire il suo personale basta richiederlo. 2) Nessun vincolo di nessun genere

Ho richiesto un auth_id a nome di "FatturaElettronicaPA Open Source" e l'ho ovviamente ottenuto. Alla luce di quanto quotato qui sopra si potrebbe pensare di avere l'auth-id settato di default in una proprietà così il codice è usabile da subito. Immagino che le richieste vengano loggate, quindi forse non è buona idea, che ne pensate? Coinvolgo anche @DiegoMartelli e @sgardini

**Comment by Deltafox79** [comment]
@nicolaiarocci  Per me è ok... anche se terrei l'eventualità di usarne uno personalizzato.. Da parte loro non credo vi sia nessun tipo di problema perchè l'uso è illimitato e gratutio sempre. gestiscono il servizio webclient non a caso altrimenti avrebbero mantenuto le richieste prettamente tramite sito web.. il servizio c'è perchè non sfruttarlo..

Ciao

**Comment by DiegoMartelli** [comment]
Ovviamente sarebbe più comodo usare un codice unico, ma se lo bacca qualche
furbacchione che decide di usarlo per un attacco poi rischia di non
funzionare più per nessuno. oltre a gli ovvi problemi per Nicola e azienda.
Se lo pescassimo dall' (app/web)config?

Il giorno mar 7 apr 2015 alle ore 16:36 Paolo <notifications@github.com> ha
scritto:

**Comment by sgardini** [comment]
Penso non ci siano problemi ad usare un unico ID per fare anche migliaia di request. Essendo un servizio non credo pongano limiti o controllino gli accessi in qualche modo.

**Comment by nicolaiarocci** [comment]
>  se lo becca qualche furbacchione che decide di usarlo per un attacco poi rischia di non
funzionare più per nessuno

E' proprio quel che intendevo.. ovvio che se vogliono fare attacco DDoS o simili possono semplicemente creare auth_id e lanciarlo ma così non devono manco dare email (usando il predefinito nel nostro codice). Direi che non è un problema imporre la impostazione esplicita.

Ci penso un po' su per quanto riguarda la scelta package indipendente/inclusione in Forms. Propendo per la prima ma ci voglio pensare con calma.

**Comment by nicolaiarocci** [comment]
Work in Progress se intanto volete dare occhiata (mancano doc e test ma in Playground c'è esempio d'uso) https://github.com/FatturaElettronicaPA/FatturaElettronicaPA.WebServices
