### ISSUE TITLE
Fattura Elettronica Body

### ISSUE THREAD

**Issue by jtpsala** [FatturaElettronica/FatturaElettronica.Forms#114]
Buonasera sig. Nicola,
sarebbe possibile avere anche un esempio su WindowsForm della parte che riguarda la compilazione della Fattura Elettronica Body, con relativa sezione visiva della validazione della Fattura e creazione del file XML?
Complimenti per il suo prezioso lavoro.

**Comment by nicolaiarocci** [comment]
Ciao, FatturaElettronica.Forms supporta solo edit del Header, non del Body, mi dispiace.
