### ISSUE TITLE
Set property Tabella.Codice is protected, Tabella.set_Codice is missing

### ISSUE THREAD

**Issue by elliskot** [FatturaElettronica/FatturaElettronica.Forms#17]
Ciao, ho preso il progetto form ed ho rimosso dalla solution i riferimenti ai progetti **FatturaElettronica** e **FatturaElettronica.Core**, ed ho aggiunto alla solution, tramite Nuget, entrambi i packetti, in modo da poterli aggiornare.
Quando compilo, in **FatturaElettronica.Forms**, mi da un errore di permessi sulla funzione di Set della proprietá **Codice**, classe **Tabella**
Controllando nel sorgente ho visto che é stata impostata la Set in modo **Protected**. 
Per far partire il progetto ho momentaneamente commentato la riga di codice che porta al problema appena descritto, e si ricompila tutto.
Avviando il progetto, peró, da errore al momento della definizione e inizializzazione della form  **FatturaElettronicaForm**:

_Tentativo di accesso al metodo 'FatturaElettronica.Tabelle.Tabella.set_Codice(System.String)' da parte del metodo 'FatturaElettronica.Forms.FatturaElettronicaForm.InitializeControls()' non riuscito_

Se navigo il codice da VS, non riesco a trovare il metodo **set_Codice** nella definizione di **Tabella**.

A questo punto ho provato a rimuovere il progetto di  **FatturaElettronica.Forms** dalla solution ed ho collegato anche questo tramite Nuget, ma mi da lo stesso errore sulla Set del campo Codice.

Puó essere che uno dei progetti non sia stato aggiornato secondo le modifiche apportate agli altri?

Grazie, ciao.

Ellis

**Comment by nicolaiarocci** [comment]
Ciao, in effetti questo progetto era rimasto indietro. Ora è aggiornato alla v1.1 di FatturaElettronica che ho rilasciato oggi.

**Comment by elliskot** [comment]
Scusami ma su Nuget ho questa situazione:
FatturaElettronica V1.1.0
FatturaElettronica.Forms **V1.0.0**
FatturaElettronica.Core V1.1.0

Ho provato ad aggiornare ma continua a propormi la 1.0.0 su Forms
Allego foto delle versioni installate

Grazie, ciao.

Ellis
![fattelet](https://user-images.githubusercontent.com/4243209/51041240-bfa67100-15b9-11e9-8a2f-34e8dc3c3e1a.png)

**Comment by nicolaiarocci** [comment]
non è ancora su nuget. dammi un minuto.

**Comment by elliskot** [comment]
Scusa non avevo notato che mi avevi appena risposto. É stato un caso che ho aggiornato appena mi hai risposto e non ho controllato. 

Grazie mille. 

Ellis

**Comment by nicolaiarocci** [comment]
dovrebbe essere indicizzato tra qualche minuto

**Comment by elliskot** [comment]
Perfetto, grazie mille, ciao.

Ellis
