### ISSUE TITLE
FatturaElettronicaForms

### ISSUE THREAD

**Issue by Brucio** [FatturaElettronica/FatturaElettronica.Forms#38]
Salve, ho creato praticamente tutta la grafica per il body per un mio progetto, volevo fare la validazione dei campi direttamente dai controlli, come ha fatto lei per l'header, però la SetDataBindings di fatto non associa il campo Body al bindingsource. Potrei fare la validazione creando un oggetto fattura da aggiungere prima della validazione, però mi piacerebbe rimanere in linea con la filosofia del progetto.
Se può darmi una mano le sarei grato.

**Comment by nicolaiarocci** [comment]
Ciao, non ho capito se stai tentando di espandere la libreria FatturaElettronica.Forms aggiungendo editing del Body, oppure se stai facendo chiedendo aiuto per un tuo lavoro. Nel primo caso prova a inviare una pull request così posso guardarci. Nel secondo, non saprei come aiutarti.

**Comment by Brucio** [comment]
Si, sto espandendo con l'edit del Body. Grazie invierò una pull. Complimenti comunque per il gran lavoro svolto, davvero notevole.
